workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH == "pipeline-testing"

image: registry.gitlab.com/ivanovkirilg/linebot

stages:
  - build
  - generic-test
  - specific-test

cmake-build:
  stage: build
  parallel:
    matrix:
      - BUILD_TYPE:
          - RelWithDebInfo
          - Debug
  script:
    - cmake -B build -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
    - cmake --build build --config ${BUILD_TYPE} -j
  artifacts:
    paths:
      - build/
    name: cmake-build-${BUILD_TYPE}

.generate-docs:
  stage: build
  script:
    - cmake -B build
    - cmake --build build --target docs
  artifacts:
    paths:
      - build/html/

generate-docs-mr:
  extends: .generate-docs
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  environment:
    name: MR/${CI_MERGE_REQUEST_IID}/Docs
    url: https://${CI_PROJECT_NAMESPACE}.gitlab.io/-/${CI_PROJECT_NAME}/-/jobs/${CI_JOB_ID}/artifacts/build/html/index.html

generate-docs-main:
  extends: .generate-docs
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  pages:
    publish: build/html

test-expected-pass:
  stage: generic-test
  parallel:
    matrix:
      - BUILD_TYPE:
          - RelWithDebInfo
          - Debug
  needs:
    - job: cmake-build
      parallel:
        matrix:
          - BUILD_TYPE: $[[matrix.BUILD_TYPE]]
  script:
    - CTEST_OPTS="--test-dir build/ --output-on-failure --timeout 5"
    - ctest $CTEST_OPTS --label-exclude "known-fail|known-unstable"
    - ctest $CTEST_OPTS --label-regex known-unstable --repeat until-pass:5

check-known-fails:
  stage: generic-test
  parallel:
    matrix:
      - BUILD_TYPE:
          - RelWithDebInfo
          - Debug
  needs:
    - job: cmake-build
      parallel:
        matrix:
          - BUILD_TYPE: $[[matrix.BUILD_TYPE]]
  script:
    # Requires CI_PRIVATE_TOKEN env variable
    - python3 ci/check_known_fails.py ${BUILD_TYPE}
  artifacts:
    paths:
      - known-fail-passed-${BUILD_TYPE}.md
    when: always
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: on_success

test-LOGR-perf:
  stage: specific-test
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - LOGR/**/*
      when: always
    - when: never
  needs: []

  script:
    - git fetch
    # Baseline build & test
    - git checkout $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    - cmake -B build/ -DCMAKE_BUILD_TYPE=RelWithDebInfo
    - cmake --build build/ -j --target LOGR_perf_baseline
    - sleep 5
    # Changed build & test
    - git checkout $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    - cmake --build build/ -j --target LOGR_perf_test
    # Requires CI_PRIVATE_TOKEN env variable
    - python3 ci/upload_sticky_comment.py --file build/LOGR_perf_comment.md
  artifacts:
    name: LOGR-perf-comment
    paths:
      - build/LOGR_perf_comment.md
      - build/LOGR_perf_*.txt
    when: always
