name: CMake on a single platform

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        build-type: [RelWithDebInfo, Debug]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build-type}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.build-type}} -j

      # Permissions are not preserved otherwise:
      - run: tar czf build.tar.gz ./build

      - name: Upload build dir
        uses: actions/upload-artifact@v4.6.2
        with:
          name: build-${{matrix.build-type}}
          path: build.tar.gz

  test:
    runs-on: ubuntu-latest
    needs: build

    strategy:
      matrix:
        build-type: [RelWithDebInfo, Debug]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Download build
        uses: actions/download-artifact@v5
        with:
          name: build-${{matrix.build-type}}

      - run: tar xzf build.tar.gz

      - name: Test
        working-directory: ${{github.workspace}}/build
        #                                                         label-exclude
        run: ctest -C ${{matrix.build-type}} --output-on-failure -LE known-fail --timeout 5

      - name: Test known failures
        working-directory: ${{github.workspace}}/build
        run: ${{github.workspace}}/.github/workflows/cmake-known-fails.bash ${{matrix.build-type}}

      - name: Upload known failures that passed
        uses: actions/upload-artifact@v4.6.2
        with:
          name: known-fail-passed-${{matrix.build-type}}-comment
          path: ${{github.workspace}}/build/known-fail-passed-*-comment.txt
          if-no-files-found: ignore
